# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
notifications:
  email: true
addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgtk-3-0
env:
  - PYTHON=""
install:
  - julia --project=. -e 'using Pkg; pkg"instantiate"'
  - julia --project=. -e 'using Pkg; pkg"status"'
before_script:
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
script:
  - julia --project=. -e 'using Pkg; pkg"test DataValues"'
  - julia --project=. -e 'using Pkg; pkg"test IteratorInterfaceExtensions"'
  - julia --project=. -e 'using Pkg; pkg"test TableTraits"'
  - julia --project=. -e 'using Pkg; pkg"test TableTraitsUtils"'
  - $TESTCMD --project=. -e 'using Pkg; pkg"test IterableTables"'
  - julia --project=. -e 'using Pkg; pkg"test QueryOperators"'
  - julia --project=. -e 'using Pkg; pkg"test Query"'
  - julia --project=. -e 'using Pkg; pkg"test FileIO"'
  - julia --project=. -e 'using Pkg; pkg"test ExcelReaders"'
  - julia --project=. -e 'using Pkg; pkg"test ExcelFiles"'
  - julia --project=. -e 'using Pkg; pkg"test ReadStat"'
  - julia --project=. -e 'using Pkg; pkg"test StatFiles"'
  - julia --project=. -e 'using Pkg; pkg"test CSVFiles"'
  - julia --project=. -e 'using Pkg; pkg"test FeatherLib"'
  - julia --project=. -e 'using Pkg; pkg"test FeatherFiles"'
  - julia --project=. -e 'using Pkg; pkg"test ParquetFiles"'
  - julia --project=. -e 'using Pkg; pkg"test QueryTables"'
  - julia --project=. -e 'using Pkg; pkg"test TableShowUtils"'
  - julia --project=. -e 'using Pkg; pkg"test VegaDatasets"'
  - $TESTCMD --project=. -e 'using Pkg; pkg"test ElectronDisplay"'
  - $TESTCMD --project=. -e 'using Pkg; pkg"test DataVoyager"'
  - $TESTCMD --project=. -e 'using Pkg; pkg"test Queryverse"'
