# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: true
addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgtk-3-0  
install:
  - julia -e 'Pkg.clone("https://github.com/davidanthoff/Queryverse.jl.git")'
  - julia -e 'ENV["PYTHON"]=""; Pkg.build("ExcelReaders")'
  - julia -e 'Pkg.status()'
before_script:
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
script:
  - julia -e 'Pkg.test("DataValues")'
  - julia -e 'Pkg.test("IteratorInterfaceExtensions")'
  - julia -e 'Pkg.test("TableTraits")'
  - julia -e 'Pkg.test("TableTraitsUtils")'
  - $TESTCMD -e 'Pkg.test("IterableTables")'
  - julia -e 'Pkg.test("QueryOperators")'
  - julia -e 'Pkg.test("Query")'
  - julia -e 'Pkg.test("FileIO")'
  - julia -e 'Pkg.test("ExcelFiles")'
  - julia -e 'Pkg.test("StatFiles")'
  - julia -e 'Pkg.test("CSVFiles")'
  - julia -e 'Pkg.test("FeatherFiles")'
  - julia -e 'Pkg.test("ParquetFiles")'
  - $TESTCMD -e 'Pkg.test("Queryverse")'
