# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: true
script:
  - julia -e 'Pkg.clone("https://github.com/davidanthoff/Dataverse.jl.git")'
  - julia -e 'Pkg.test("DataValues")'
  - julia -e 'Pkg.test("IterableTables")'
  - julia -e 'Pkg.test("Query")'
  - julia -e 'Pkg.test("FileIO")'
  - julia -e 'Pkg.test("ExcelFiles")'
  - julia -e 'Pkg.test("StatFiles")'
  - julia -e 'Pkg.test("CSVFiles")'
  - julia -e 'Pkg.test("FeatherFiles")'
  - julia -e 'Pkg.test("DataFrames")'
  - julia -e 'Pkg.test("Dataverse")'
