# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 1.0
notifications:
  email: true
addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgtk-3-0  
env:
  - PYTHON=""  
install:
  - julia -e 'using Pkg; pkg"add Queryverse"'
  - julia -e 'using Pkg; pkg"status"'
before_script:
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
script:
  - julia -e 'using Pkg; pkg"test DataValues"'
  - julia -e 'using Pkg; pkg"test IteratorInterfaceExtensions"'
  - julia -e 'using Pkg; pkg"test TableTraits"'
  - julia -e 'using Pkg; pkg"test TableTraitsUtils"'
  - $TESTCMD -e 'using Pkg; pkg"test IterableTables"'
  - julia -e 'using Pkg; pkg"test QueryOperators"'
  - julia -e 'using Pkg; pkg"test Query"'
  - julia -e 'using Pkg; pkg"test FileIO"'
  - julia -e 'using Pkg; pkg"test ExcelFiles"'
  - julia -e 'using Pkg; pkg"test StatFiles"'
  - julia -e 'using Pkg; pkg"test CSVFiles"'
  - julia -e 'using Pkg; pkg"test FeatherFiles"'
  - julia -e 'using Pkg; pkg"test ParquetFiles"'
  - $TESTCMD -e 'using Pkg; pkg"test Queryverse"'
